version: 2.1

orbs:
  node: circleci/node@1.1.6

executors:
  node:
    working_directory: ~
    docker:
      - image: circleci/node:12

commands:
  get-schema:
    steps:
      - run: curl $SCHEMA_URL -sL -o $SCHEMA_PATH
  node-install:
    steps:
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile

jobs:
  install:
    executor:
      name: node
    steps:
      - checkout
      - node-install
  lint:
    executor:
      name: node
    steps:
      - checkout
      - node-install
      - get-schema
      - run: mkdir reports
      - run: npm run prebuild
      - run:
          command: npm run lint:prettier
          when: always
      - run:
          command: npm run lint:tsc
          when: always
      - run:
          command: npm run -s lint:stylelint -- --custom-formatter node_modules/stylelint-junit-formatter > reports/stylelint.xml
          when: always
      - run:
          command: npm run -s lint:eslint  -- --format junit --output-file reports/eslint.xml
          when: always
      - store_test_results:
          path: reports
  build:
    executor:
      name: node
    steps:
      - checkout
      - node-install
      - get-schema
      - run: npm run build

workflows:
  main:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
