version: 2.1

orbs:
  node: circleci/node@1.1

executors:
  node:
    working_directory: ~
    docker:
      - image: circleci/node:12.14.1

commands:
  get-schema:
    steps:
      - run: curl $SCHEMA_URL -sL -o $SCHEMA_PATH
  node-install:
    steps:
      - node/with-cache:
          steps:
            - run: npm ci

jobs:
  install:
    executor:
      name: node
    steps:
      - checkout
      - node-install
  lint:
    executor:
      name: node
    steps:
      - checkout
      - node-install
      - get-schema
      - run: npm run prebuild
      - run: npm run lint:prettier
      - run: npm run lint:eslint -- --format junit --output-file lint-results/eslint.xml
      - store_test_results:
          path: lint-results
  build:
    executor:
      name: node
    steps:
      - checkout
      - node-install
      - get-schema
      - run: npm run build

workflows:
  main:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
