version: 2.1

orbs:
  node: circleci/node@1.1

jobs:
  install:
    executor:
      name: node/default
      tag: "12"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci

workflows:
  main:
    jobs:
      - install
